name: Run algolia docsearch

on:
  push:
    branches:
      - main
      - 'ci/docsearch'

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & upload Algolia index
        uses: razonyang/hugo-theme-bootstrap-algolia-action@v0.1.1
        with:
          algolia-app-id: ${{ secrets.ALGOLIA_DOCSEARCH_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_DOCSEARCH_API_KEY }}
          algolia-index-name: docs_nevermined_app        